# Generated by Django 4.0.5 on 2022-07-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Finished', 'Finished')], max_length=20)),
            ],
        ),
    ]
